version: "3"
services:
  app:
    build: .
    container_name: linkshortener
    ports: 
      - 8000:8000
    depends_on: 
      - postgres
    command: "/bin/wait-for-it.sh postgres:5432 -t 10 -- /bin/linkshortener serve"

  postgres: 
    image: postgres:12
    container_name: postgres 
    env_file: ./.env
    ports: 
      - 8001:5432
    volumes: 
      - ./pg_data:/var/lib/postgresql/data
    
volumes: 
  pg_data: